In [2]:
import pandas as pd
import requests

In [3]:
url="https://v6.exchangerate-api.com/v6/0e0ce298ff97b0e9b38cb3ef/latest/USD"

In [5]:
response=requests.get(url)

In [6]:
if response.status_code==200:
    data=response.json() #we get in dictionary format

In [24]:
data

{'result': 'success',
 'documentation': 'https://www.exchangerate-api.com/docs',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1745452801,
 'time_last_update_utc': 'Thu, 24 Apr 2025 00:00:01 +0000',
 'time_next_update_unix': 1745539201,
 'time_next_update_utc': 'Fri, 25 Apr 2025 00:00:01 +0000',
 'base_code': 'USD',
 'conversion_rates': {'USD': 1,
  'AED': 3.6725,
  'AFN': 71.5496,
  'ALL': 86.5125,
  'AMD': 390.3568,
  'ANG': 1.79,
  'AOA': 919.4288,
  'ARS': 1122.5,
  'AUD': 1.566,
  'AWG': 1.79,
  'AZN': 1.7004,
  'BAM': 1.7235,
  'BBD': 2.0,
  'BDT': 121.4845,
  'BGN': 1.7225,
  'BHD': 0.376,
  'BIF': 2958.7069,
  'BMD': 1.0,
  'BND': 1.314,
  'BOB': 6.9114,
  'BRL': 5.7072,
  'BSD': 1.0,
  'BTN': 85.4532,
  'BWP': 13.6665,
  'BYN': 3.0484,
  'BZD': 2.0,
  'CAD': 1.3865,
  'CDF': 2892.0463,
  'CHF': 0.8276,
  'CLP': 944.7605,
  'CNY': 7.2957,
  'COP': 4294.9828,
  'CRC': 502.4687,
  'CUP': 24.0,
  'CVE': 97.1696,
  'CZK': 22.0113,
  'DJF': 177.721,
  'DKK': 6.579,
  'DOP': 59.4754,
  'DZD': 132.2186,
  'EGP': 50.955,
  'ERN': 15.0,
  'ETB': 132.8961,
  'EUR': 0.8812,
  'FJD': 2.2539,
  'FKP': 0.7533,
  'FOK': 6.5789,
  'GBP': 0.7533,
  'GEL': 2.7485,
  'GGP': 0.7533,
  'GHS': 15.3662,
  'GIP': 0.7533,
  'GMD': 72.525,
  'GNF': 8672.3448,
  'GTQ': 7.6925,
  'GYD': 208.8071,
  'HKD': 7.76,
  'HNL': 25.9002,
  'HRK': 6.6397,
  'HTG': 130.4856,
  'HUF': 359.8388,
  'IDR': 16881.7598,
  'ILS': 3.6527,
  'IMP': 0.7533,
  'INR': 85.4537,
  'IQD': 1307.2416,
  'IRR': 41892.154,
  'ISK': 127.0577,
  'JEP': 0.7533,
  'JMD': 158.1321,
  'JOD': 0.709,
  'JPY': 142.7087,
  'KES': 129.4027,
  'KGS': 86.6262,
  'KHR': 3987.0141,
  'KID': 1.5666,
  'KMF': 433.5402,
  'KRW': 1424.7506,
  'KWD': 0.3062,
  'KYD': 0.8333,
  'KZT': 518.8025,
  'LAK': 21692.7781,
  'LBP': 89500.0,
  'LKR': 299.2339,
  'LRD': 199.9794,
  'LSL': 18.6425,
  'LYD': 5.4253,
  'MAD': 9.251,
  'MDL': 17.1971,
  'MGA': 4524.0705,
  'MKD': 53.794,
  'MMK': 2096.4884,
  'MNT': 3567.0664,
  'MOP': 7.9928,
  'MRU': 39.4989,
  'MUR': 44.8662,
  'MVR': 15.4428,
  'MWK': 1736.799,
  'MXN': 19.6247,
  'MYR': 4.3922,
  'MZN': 63.8044,
  'NAD': 18.6425,
  'NGN': 1603.9463,
  'NIO': 36.7431,
  'NOK': 10.4742,
  'NPR': 136.7252,
  'NZD': 1.6756,
  'OMR': 0.3845,
  'PAB': 1.0,
  'PEN': 3.6943,
  'PGK': 4.076,
  'PHP': 56.5668,
  'PKR': 281.2793,
  'PLN': 3.7731,
  'PYG': 8006.9049,
  'QAR': 3.64,
  'RON': 4.3701,
  'RSD': 102.776,
  'RUB': 82.821,
  'RWF': 1439.3869,
  'SAR': 3.75,
  'SBD': 8.534,
  'SCR': 14.6413,
  'SDG': 543.2068,
  'SEK': 9.6574,
  'SGD': 1.314,
  'SHP': 0.7533,
  'SLE': 22.6792,
  'SLL': 22679.1864,
  'SOS': 570.5213,
  'SRD': 36.6401,
  'SSP': 4518.3091,
  'STN': 21.5903,
  'SYP': 12914.2176,
  'SZL': 18.6425,
  'THB': 33.4407,
  'TJS': 10.7165,
  'TMT': 3.4952,
  'TND': 2.9889,
  'TOP': 2.3601,
  'TRY': 38.3553,
  'TTD': 6.7692,
  'TVD': 1.5666,
  'TWD': 32.479,
  'TZS': 2682.9379,
  'UAH': 41.7352,
  'UGX': 3648.1696,
  'UYU': 42.18,
  'UZS': 12879.0636,
  'VES': 83.4182,
  'VND': 25986.5443,
  'VUV': 119.1151,
  'WST': 2.76,
  'XAF': 578.0536,
  'XCD': 2.7,
  'XCG': 1.79,
  'XDR': 0.7368,
  'XOF': 578.0536,
  'XPF': 105.1598,
  'YER': 244.8424,
  'ZAR': 18.6477,
  'ZMW': 28.4631,
  'ZWL': 26.8204}}

In [33]:
rates=data["conversion_rates"]
rates.items()# it gives a list of tuples with kiey and value pairs

dict_items([('USD', 1), ('AED', 3.6725), ('AFN', 71.5496), ('ALL', 86.5125), ('AMD', 390.3568), ('ANG', 1.79), ('AOA', 919.4288), ('ARS', 1122.5), ('AUD', 1.566), ('AWG', 1.79), ('AZN', 1.7004), ('BAM', 1.7235), ('BBD', 2.0), ('BDT', 121.4845), ('BGN', 1.7225), ('BHD', 0.376), ('BIF', 2958.7069), ('BMD', 1.0), ('BND', 1.314), ('BOB', 6.9114), ('BRL', 5.7072), ('BSD', 1.0), ('BTN', 85.4532), ('BWP', 13.6665), ('BYN', 3.0484), ('BZD', 2.0), ('CAD', 1.3865), ('CDF', 2892.0463), ('CHF', 0.8276), ('CLP', 944.7605), ('CNY', 7.2957), ('COP', 4294.9828), ('CRC', 502.4687), ('CUP', 24.0), ('CVE', 97.1696), ('CZK', 22.0113), ('DJF', 177.721), ('DKK', 6.579), ('DOP', 59.4754), ('DZD', 132.2186), ('EGP', 50.955), ('ERN', 15.0), ('ETB', 132.8961), ('EUR', 0.8812), ('FJD', 2.2539), ('FKP', 0.7533), ('FOK', 6.5789), ('GBP', 0.7533), ('GEL', 2.7485), ('GGP', 0.7533), ('GHS', 15.3662), ('GIP', 0.7533), ('GMD', 72.525), ('GNF', 8672.3448), ('GTQ', 7.6925), ('GYD', 208.8071), ('HKD', 7.76), ('HNL', 25.9002), ('HRK', 6.6397), ('HTG', 130.4856), ('HUF', 359.8388), ('IDR', 16881.7598), ('ILS', 3.6527), ('IMP', 0.7533), ('INR', 85.4537), ('IQD', 1307.2416), ('IRR', 41892.154), ('ISK', 127.0577), ('JEP', 0.7533), ('JMD', 158.1321), ('JOD', 0.709), ('JPY', 142.7087), ('KES', 129.4027), ('KGS', 86.6262), ('KHR', 3987.0141), ('KID', 1.5666), ('KMF', 433.5402), ('KRW', 1424.7506), ('KWD', 0.3062), ('KYD', 0.8333), ('KZT', 518.8025), ('LAK', 21692.7781), ('LBP', 89500.0), ('LKR', 299.2339), ('LRD', 199.9794), ('LSL', 18.6425), ('LYD', 5.4253), ('MAD', 9.251), ('MDL', 17.1971), ('MGA', 4524.0705), ('MKD', 53.794), ('MMK', 2096.4884), ('MNT', 3567.0664), ('MOP', 7.9928), ('MRU', 39.4989), ('MUR', 44.8662), ('MVR', 15.4428), ('MWK', 1736.799), ('MXN', 19.6247), ('MYR', 4.3922), ('MZN', 63.8044), ('NAD', 18.6425), ('NGN', 1603.9463), ('NIO', 36.7431), ('NOK', 10.4742), ('NPR', 136.7252), ('NZD', 1.6756), ('OMR', 0.3845), ('PAB', 1.0), ('PEN', 3.6943), ('PGK', 4.076), ('PHP', 56.5668), ('PKR', 281.2793), ('PLN', 3.7731), ('PYG', 8006.9049), ('QAR', 3.64), ('RON', 4.3701), ('RSD', 102.776), ('RUB', 82.821), ('RWF', 1439.3869), ('SAR', 3.75), ('SBD', 8.534), ('SCR', 14.6413), ('SDG', 543.2068), ('SEK', 9.6574), ('SGD', 1.314), ('SHP', 0.7533), ('SLE', 22.6792), ('SLL', 22679.1864), ('SOS', 570.5213), ('SRD', 36.6401), ('SSP', 4518.3091), ('STN', 21.5903), ('SYP', 12914.2176), ('SZL', 18.6425), ('THB', 33.4407), ('TJS', 10.7165), ('TMT', 3.4952), ('TND', 2.9889), ('TOP', 2.3601), ('TRY', 38.3553), ('TTD', 6.7692), ('TVD', 1.5666), ('TWD', 32.479), ('TZS', 2682.9379), ('UAH', 41.7352), ('UGX', 3648.1696), ('UYU', 42.18), ('UZS', 12879.0636), ('VES', 83.4182), ('VND', 25986.5443), ('VUV', 119.1151), ('WST', 2.76), ('XAF', 578.0536), ('XCD', 2.7), ('XCG', 1.79), ('XDR', 0.7368), ('XOF', 578.0536), ('XPF', 105.1598), ('YER', 244.8424), ('ZAR', 18.6477), ('ZMW', 28.4631), ('ZWL', 26.8204)])

In [34]:
conversion_table=pd.DataFrame(rates.items(),columns=["currecy","current exchange rate"])

In [35]:
conversion_table

    currecy  current exchange rate
0       USD                 1.0000
1       AED                 3.6725
2       AFN                71.5496
3       ALL                86.5125
4       AMD               390.3568
..      ...                    ...
158     XPF               105.1598
159     YER               244.8424
160     ZAR                18.6477
161     ZMW                28.4631
162     ZWL                26.8204

[163 rows x 2 columns]

In [37]:
conversion_table.to_csv("conversion.csv")